dataset:
  num_classes: 2
  mode: Micro
  datatype: CAS
  training:
    ngpu: 1
    video_data_path: ../datasets/face/emotion/npy/CAS/Micro/npy
    video_info_path: ../datasets/face/emotion/npy/CAS/Micro/label
    video_anno_path: ../datasets/face/emotion/npy/CAS/Micro/label/
    clip_length: 256
    clip_stride: 30
    crop_size: 96
  testing:
    video_data_path: ../datasets/face/emotion/npy/CAS/Micro/npy
    video_info_path: ../datasets/face/emotion/npy/CAS/Micro/label/
    clip_length: 256
    clip_stride: 128
    crop_size: 96

model:
  in_channels: 2
  freeze_bn: true
  freeze_bn_affine: true
  backbone_model: ../weight/i3d_models/flow_imagenet.pt

training:
  batch_size: 1
  learning_rate: 1e-5
  weight_decay: 1e-3
  max_epoch: 16
  focal_loss: true
  checkpoint_path: ../weight/
  random_seed: 2020

testing:
  conf_thresh: 0.1
  top_k: 20
  nms_sigma: 0.5
